
SRC_ROOT := $(PWD)/../../..
CONFIG_USED = $(SRC_ROOT)/sample/config/include

EXTRA_CFLAGS += -O0 -I$(KERNELDIR)/include -Wno-format -DICC_GCC_ARM -fshort-enums -DICC_MIX_32_64_SUPPORT -DICC_LINUX2LINUX -DICC_USE_POLLING

ifeq ($(CONFIG),EP)
    EXTRA_CFLAGS += -DICC_BUILD_FOR_M4
endif

ifeq ($(CONFIG),BB_RC)
    EXTRA_CFLAGS += -DICC_PCIE_SHMEM_BLUEBOX
endif

ifeq ($(CONFIG),BB_EP)
    EXTRA_CFLAGS += -DICC_BUILD_FOR_M4 -DICC_PCIE_SHMEM_BLUEBOX
endif

INCLUDE_DEPENDENCIES := -I$(SRC_ROOT)/code/linux/inc \
                        -I$(SRC_ROOT)/code/linux/os \
                        -I$(SRC_ROOT)/code/linux/os/Linux \
                        -I$(SRC_ROOT)/code/linux/hw \
                        -I$(CONFIG_USED)\
                        -I$(PWD)

ifneq ($(CC),$(LD))
	# bitbake calls $(CROSS_COMPILE)LD for linking instead of $(CROSS_COMPILE)GCC
	# and we need to update LDFLAGS for this case
	LDFLAGS := -O0 --hash-style=gnu --as-needed
endif

## Objects to build ##
obj-m := ICC_dev_$(CONFIG).o
ccflags-y += $(INCLUDE_DEPENDENCIES)
ICC_dev_$(CONFIG)-objs := ./ICC_lib.o
ICC_dev_$(CONFIG)-objs += ../../../code/linux/src/ICC_Api.o
ICC_dev_$(CONFIG)-objs += ../../../code/linux/src/ICC_Sig_Fifo.o
ICC_dev_$(CONFIG)-objs += ../../../code/linux/src/ICC_Fifo.o
ICC_dev_$(CONFIG)-objs += ../../../code/linux/os/Linux/ICC_Os_Linux.o

