
# CONFIG must be one of RTOS, EP, RC
ifeq ($(findstring $(CONFIG),RTOS EP RC),)
    $(error CONFIG not defined or invalid)
endif

SRC_ROOT := $(PWD)/../../..
CONFIG_USED := $(SRC_ROOT)/sample/config/include

EXTRA_CFLAGS += -O0 -I$(KERNELDIR)/include -Wno-format -DICC_GCC_ARM -DICC_MIX_32_64_SUPPORT

ifeq ($(findstring $(CONFIG),EP RC),$(CONFIG))
    EXTRA_CFLAGS += -DICC_LINUX2LINUX -DICC_USE_POLLING
endif

ifeq ($(CONFIG),EP)
    EXTRA_CFLAGS += -DICC_BUILD_FOR_M4
endif

INCLUDE_DEPENDENCIES := -I$(SRC_ROOT)/code/linux/inc \
                        -I$(SRC_ROOT)/code/linux/os \
                        -I$(SRC_ROOT)/code/linux/os/Linux \
                        -I$(SRC_ROOT)/code/linux/hw \
                        -I$(CONFIG_USED)\
                        -I$(PWD)

ifneq ($(CC),$(LD))
	# bitbake calls $(CROSS_COMPILE)LD for linking instead of $(CROSS_COMPILE)GCC
	# and we need to update LDFLAGS for this case
	LDFLAGS := -O0 --hash-style=gnu --as-needed
endif

## Objects to build ##
COMMON_OBJS := ./ICC_lib.o ICC_Notification.o
COMMON_OBJS += ../../../code/linux/src/ICC_Api.o
COMMON_OBJS += ../../../code/linux/src/ICC_Sig_Fifo.o
COMMON_OBJS += ../../../code/linux/src/ICC_Fifo.o
COMMON_OBJS += ../../../code/linux/os/Linux/ICC_Os_Linux.o

ifeq ($(CONFIG),RTOS)
obj-m := ICC_dev.o
ICC_dev-objs := $(COMMON_OBJS)
ICC_dev-objs += ./ICC_Interrupts.o
else
obj-m := ICC_dev_$(CONFIG).o
ICC_dev_$(CONFIG)-objs := $(COMMON_OBJS)
ICC_dev_$(CONFIG)-objs += ./ICC_Pcie.o
ICC_dev_$(CONFIG)-objs += ./ICC_Polling.o
endif

ccflags-y += $(INCLUDE_DEPENDENCIES)
